### ISSUE TITLE
Course Engagement Plot

### ISSUE THREAD

**Issue by howardbaik** [FredHutch/itn-dashboard#13]
Add https://github.com/fhdsl/itn-metric/blob/main/last_plot.Rmd

**Comment by howardbaik** [comment]
@carriewright11 I think this is the plot you had added last. 

Two questions:

1. Do you remember how you got `course_engagement.csv`? I would like to automate data ingestion of this csv file for this dashboard. 
2. This is what this plot currently looks like:
<img width="1080" alt="Screenshot 2024-03-21 at 9 36 42 AM" src="https://github.com/FredHutch/itn-dashboard/assets/50791792/17abf631-33e2-45f1-9bc4-1191fe454983">

Should I just get rid of leanpub? It's looking a bit hollow in the middle :)

**Comment by cansavvy** [comment]
I would like to get rid of leanpub too but due to the nature of our grant we have to have a way to allow people to get certifications for free and that's what leanpub does. So we have to keep it even though its audience is not very large. If we get rid of it on the dashboard people won't realize we are still offering it.

**Comment by howardbaik** [comment]
Thx for the feedback @cansavvy. Since we need to keep Leanpub data in this plot, I will just free up the scale so that the Leanpub bar don't look miniscule.

**Comment by cansavvy** [comment]
Sounds like a good plan @howardbaek !

**Comment by howardbaik** [comment]
Thanks to @kweav , I found the data source: https://docs.google.com/spreadsheets/d/1-8vox2LzkVKzhmSFXCWjwt3jFtK-wHibRAq2fqbxEyo/edit#gid=36452562
