### ISSUE TITLE
Aesthetics

### ISSUE THREAD

**Issue by cansavvy** [FredHutch/itn-dashboard#2]
@howardbaek This is a great start! Very exciting! 

I will add in the automation components so the data is automatically updated. 

In the meanwhile some minor requests: 

- Captions - how can we add captions to these plots? I don't necessarily need you to write them by yourself, but where would we add them in? 
- Rounding the numbers -- in the table can we round the numbers to maybe 2 decimal places?

**Comment by howardbaik** [comment]
Is there a hard requirement to adding captions, which would be located at the bottom right of the plot? All our plots have long x-axis labels since they are all course names, so it's hard to find the caption:

![Screenshot 2024-02-07 at 5 38 59 PM](https://github.com/FredHutch/itn-dashboard/assets/50791792/dba94c0f-7366-4534-b38b-820d0147c88c)


What do you think of adding subtitles, which would be located right below the title of the plot? It seems easier to spot:

![Screenshot 2024-02-07 at 5 39 05 PM](https://github.com/FredHutch/itn-dashboard/assets/50791792/b8bfd2d9-00c0-4e4f-af17-acf69a3a694e)
